//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Foundation.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ProductDetail : IEntityBase
    {
        public int Id { get; set; }
        public int DetailID { get; set; }
        public int ProductID { get; set; }
        public string RingTemplate { get; set; }
        public string Jewel { get; set; }
        public string MainJewel { get; set; }
    }
}
