//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Foundation.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Token : IEntityBase
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Token { get; set; }
        public string TokenType { get; set; }
        public System.DateTime ExpireDt { get; set; }
    }
}
